// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package database

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, created_at, updated_at, email)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1
  )
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreateCustomer(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const deleteAllCustomers = `-- name: DeleteAllCustomers :exec
DELETE FROM customers
`

func (q *Queries) DeleteAllCustomers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCustomers)
	return err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, created_at, updated_at, email FROM customers
WHERE email = $1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
