// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, created_at, updated_at, email, name, pax, requested_tour_id, requested_date, booking_id)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
  )
RETURNING id, created_at, updated_at, email, name, pax, status, requested_tour_id, requested_date, booking_id
`

type CreateGroupParams struct {
	Email           string
	Name            string
	Pax             int32
	RequestedTourID int32
	RequestedDate   time.Time
	BookingID       int32
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.Email,
		arg.Name,
		arg.Pax,
		arg.RequestedTourID,
		arg.RequestedDate,
		arg.BookingID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Pax,
		&i.Status,
		&i.RequestedTourID,
		&i.RequestedDate,
		&i.BookingID,
	)
	return i, err
}

const deleteAllGroups = `-- name: DeleteAllGroups :exec
DELETE FROM groups
`

func (q *Queries) DeleteAllGroups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllGroups)
	return err
}

const getGroupByEmail = `-- name: GetGroupByEmail :one
SELECT id, created_at, updated_at, email, name, pax, status, requested_tour_id, requested_date, booking_id FROM groups
WHERE email = $1
`

func (q *Queries) GetGroupByEmail(ctx context.Context, email string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByEmail, email)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Pax,
		&i.Status,
		&i.RequestedTourID,
		&i.RequestedDate,
		&i.BookingID,
	)
	return i, err
}

const groupStatusAccepted = `-- name: GroupStatusAccepted :one
UPDATE groups
SET status = 'accepted'
WHERE id = $1
RETURNING id, created_at, updated_at, email, name, pax, status, requested_tour_id, requested_date, booking_id
`

func (q *Queries) GroupStatusAccepted(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, groupStatusAccepted, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Pax,
		&i.Status,
		&i.RequestedTourID,
		&i.RequestedDate,
		&i.BookingID,
	)
	return i, err
}
