// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type GroupStatus string

const (
	GroupStatusUnhandled      GroupStatus = "unhandled"
	GroupStatusPaymentPending GroupStatus = "payment_pending"
	GroupStatusConfirmed      GroupStatus = "confirmed"
	GroupStatusCancelled      GroupStatus = "cancelled"
)

func (e *GroupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupStatus(s)
	case string:
		*e = GroupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupStatus: %T", src)
	}
	return nil
}

type NullGroupStatus struct {
	GroupStatus GroupStatus
	Valid       bool // Valid is true if GroupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GroupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupStatus), nil
}

type Group struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	Name            string
	Pax             int32
	Status          GroupStatus
	RequestedTourID int32
	RequestedDate   time.Time
}

type Tour struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	BasePrice string
}
