#!/bin/sh

echo "seeding demo user..."

curl -s -X POST http://backend:8080/api/users \
  -H "Content-Type: application/json" \
  -d '{
    "password": "password",
    "email": "test@email.com",
    "name": "Test McTestson"
  }'

echo "email: test@email.com\npassword: password"

