FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.20.0

FROM alpine:3.19
RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations
COPY sql/schema/ /migrations/

ENTRYPOINT ["goose"]
