// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tours.sql

package database

import (
	"context"
)

const createTour = `-- name: CreateTour :one
INSERT INTO tours (created_at, updated_at, name, base_price)
VALUES (
  NOW(),
  NOW(),
  $1,
  $2
  )
RETURNING id, name, created_at, updated_at, base_price
`

type CreateTourParams struct {
	Name      string
	BasePrice string
}

func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error) {
	row := q.db.QueryRowContext(ctx, createTour, arg.Name, arg.BasePrice)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BasePrice,
	)
	return i, err
}

const deleteAllTours = `-- name: DeleteAllTours :exec
DELETE FROM tours
`

func (q *Queries) DeleteAllTours(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTours)
	return err
}

const getAllTours = `-- name: GetAllTours :many
SELECT id, name, created_at, updated_at, base_price FROM tours
`

func (q *Queries) GetAllTours(ctx context.Context) ([]Tour, error) {
	rows, err := q.db.QueryContext(ctx, getAllTours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tour
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BasePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourByName = `-- name: GetTourByName :one
SELECT id, name, created_at, updated_at, base_price FROM tours
WHERE name = $1
`

func (q *Queries) GetTourByName(ctx context.Context, name string) (Tour, error) {
	row := q.db.QueryRowContext(ctx, getTourByName, name)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BasePrice,
	)
	return i, err
}
